NHL_ABBREVIATION_MAP = {
    "L.A": "LAK",
    "T.B": "TBL",
    "N.J": "NJD",
    "S.J": "SJS",
}

NHL_NAMES_MAP = {
    "ANA" : "Anaheim Ducks",
    "ARI" : "Arizona Coyotes",
    "ATL" : "Atlanta Thrashers",
    "BOS" : "Boston Bruins",
    "BUF" : "Buffalo Sabres",
    "CGY" : "Calgary Flames",
    "CAR" : "Carolina Hurricanes",
    "CHI" : "Chicago Blackhawks",
    "COL" : "Colorado Avalanche",
    "CBJ" : "Columbus Blue Jackets",
    "DAL" : "Dallas Stars",
    "DET" : "Detroit Red Wings",
    "EDM" : "Edmonton Oilers",
    "FLA" : "Florida Panthers",
    "LAK" : "Los Angeles Kings",
    "L.A" : "Los Angeles Kings",
    "MIN" : "Minnesota Wild",
    "MTL" : "Montreal Canadiens",
    "NSH" : "Nashville Predators",
    "NJD" : "New Jersey Devils",
    "N.J" : "New Jersey Devils",
    "NYI" : "New York Islanders",
    "NYR" : "New York Rangers",
    "OTT" : "Ottawa Senators",
    "PHX" : "Phoenix Coyotes",
    "PHI" : "Philadelphia Flyers",
    "PIT" : "Pittsburgh Penguins",
    "SJS" : "San Jose Sharks",
    "S.J" : "San Jose Sharks",
    "SEA" : "Seattle Kraken",
    "STL" : "St. Louis Blues",
    "TBL" : "Tampa Bay Lightning",
    "T.B" : "Tampa Bay Lightning",
    "TOR" : "Toronto Maple Leafs",
    "UTA" : "Utah Mammoth",
    "VAN" : "Vancouver Canucks",
    "VGK" : "Vegas Golden Knights",
    "WSH" : "Washington Capitals",
    "WPG" : "Winnipeg Jets",
}

NHL_NAMES_MAP_REVERSED = {
    "Anaheim Ducks" : "ANA",
    "Arizona Coyotes" : "ARI",
    "Atlanta Thrashers" : "ATL",
    "Boston Bruins" : "BOS",
    "Buffalo Sabres" : "BUF",
    "Calgary Flames" : "CGY",
    "Carolina Hurricanes" : "CAR",
    "Chicago Blackhawks" : "CHI",
    "Colorado Avalanche" : "COL",
    "Columbus Blue Jackets" : "CBJ",
    "Dallas Stars" : "DAL",
    "Detroit Red Wings" : "DET",
    "Edmonton Oilers" : "EDM",
    "Florida Panthers" : "FLA",
    "Los Angeles Kings" : "LAK",
    "Minnesota Wild" : "MIN",
    "Montréal Canadiens" : "MTL",
    "Nashville Predators" : "NSH",
    "New Jersey Devils" : "NJD",
    "New York Islanders" : "NYI",
    "New York Rangers" : "NYR",
    "Ottawa Senators" : "OTT",
    "Phoenix Coyotes" : "ARI",
    "Philadelphia Flyers" : "PHI",
    "Pittsburgh Penguins" : "PIT",
    "San Jose Sharks" : "SJS",
    "Seattle Kraken" : "SEA",
    "St. Louis Blues" : "STL",
    "Tampa Bay Lightning" : "TBL",
    "Toronto Maple Leafs" : "TOR",
    "Utah Hockey Club" : "UTA",
    "Utah Mammoth" : "UTA",
    "Vancouver Canucks" : "VAN",
    "Vegas Golden Knights" : "VGK",
    "Washington Capitals" : "WSH",
    "Winnipeg Jets" : "WPG",
}
